### ISSUE TITLE
Format Int32 is used with Type: number in multiple schemas

### ISSUE THREAD

**Issue by savage-alex** [hookdeck/hookdeck-openapi-schema#6]
When loading the OpenAPI the validator complained that there were properties whos type was "number" but had a format of "int32".

Normally type Number will have the format of double or float and type Integer will have the format int32 or int64

This was seen in the error schema as well as the ratelimit limit schema. Likely elsewhere too

**Comment by adnanh** [comment]
Very good catch! Thank you :-)
