### ISSUE TITLE
Format date is used on multiple properties but examples are date time

### ISSUE THREAD

**Issue by savage-alex** [hookdeck/hookdeck-openapi-schema#7]
Noticed that your properties of type string and format date have examples that are date-times.

![image](https://user-images.githubusercontent.com/25430683/186457046-775a33f6-e920-43ac-a78a-1018d85a7b62.png)

If the response is in ISO date time the property would be format: date-time

**Comment by adnanh** [comment]
Very good catch! Thank you :-)
